name: Create README and Website from YAML

on:
  workflow_dispatch:
  push:
    branches:  [main]
    paths: 
      - 'resources.yaml'

jobs:
  serve_user:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Change this to your Python version if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create README from YAML
      run: python scripts/yaml_to_readme.py
    - name: Create docs from YAML
      run: python scripts/yaml_to_docs.py

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update README.md"
        git push
